package frc.robot.autonomous.enums;

public enum Objective {
    BOTH_FRONT_CARGO_LEFT, BOTH_FRONT_CARGO_RIGHT,
    SIDE_CARGO_FRONT, SIDE_CARGO_MIDDLE, SIDE_CARGO_BACK,
    BOTH_LEFT_ROCKET, BOTH_RIGHT_ROCKET,
    CARGO_ROCKET_LEFT, CARGO_ROCKET_RIGHT,
    MANUAL
}